global:
  scrape_interval: 5s  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s  # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'  # Alertmanager instance (adjust if necessary)

rule_files:
  - "alerts.yml"  # Path to your alert rule file

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]  # Prometheus instance

  - job_name: 'jenkins'
    metrics_path: /prometheus/
    static_configs:
      - targets: ['localhost:8080']  # Jenkins instance (Ensure Jenkins Prometheus plugin is installed and configured)

  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['localhost:9182']  # Node Exporter for system metrics

# Additional Prometheus scraping configuration
